// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ploto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataLinkAgeServiceClient is the client API for DataLinkAgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataLinkAgeServiceClient interface {
	PreloadToken(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListAlls, error)
}

type dataLinkAgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataLinkAgeServiceClient(cc grpc.ClientConnInterface) DataLinkAgeServiceClient {
	return &dataLinkAgeServiceClient{cc}
}

func (c *dataLinkAgeServiceClient) PreloadToken(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListAlls, error) {
	out := new(ListAlls)
	err := c.cc.Invoke(ctx, "/dataLinkAge.DataLinkAgeService/PreloadToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataLinkAgeServiceServer is the server API for DataLinkAgeService service.
// All implementations must embed UnimplementedDataLinkAgeServiceServer
// for forward compatibility
type DataLinkAgeServiceServer interface {
	PreloadToken(context.Context, *ListRequest) (*ListAlls, error)
	mustEmbedUnimplementedDataLinkAgeServiceServer()
}

// UnimplementedDataLinkAgeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataLinkAgeServiceServer struct {
}

func (UnimplementedDataLinkAgeServiceServer) PreloadToken(context.Context, *ListRequest) (*ListAlls, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreloadToken not implemented")
}
func (UnimplementedDataLinkAgeServiceServer) mustEmbedUnimplementedDataLinkAgeServiceServer() {}

// UnsafeDataLinkAgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataLinkAgeServiceServer will
// result in compilation errors.
type UnsafeDataLinkAgeServiceServer interface {
	mustEmbedUnimplementedDataLinkAgeServiceServer()
}

func RegisterDataLinkAgeServiceServer(s grpc.ServiceRegistrar, srv DataLinkAgeServiceServer) {
	s.RegisterService(&DataLinkAgeService_ServiceDesc, srv)
}

func _DataLinkAgeService_PreloadToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataLinkAgeServiceServer).PreloadToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataLinkAge.DataLinkAgeService/PreloadToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataLinkAgeServiceServer).PreloadToken(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataLinkAgeService_ServiceDesc is the grpc.ServiceDesc for DataLinkAgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataLinkAgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataLinkAge.DataLinkAgeService",
	HandlerType: (*DataLinkAgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreloadToken",
			Handler:    _DataLinkAgeService_PreloadToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dataUserLinkAge.proto",
}
